### ISSUE TITLE
Subset-26 conversion to ProR

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#218]
# Design Spec: Subset-26 conversion to ProR

The objective of this tool is to convert the MS Word-based Subset-26 to the ProR-based ReqIF format.  Important is the ability to do subsequent updates with an updated  Subset and the availability of section numbers as human- and machine-readable IDs.

Note that the question of _Traceability_ is outside the scope of this issue.
# TODO
- [x] Find someone who has access to DOORS 9.4, or find an academic partner who is willing to acquire (and install) the free academic version of DOORS 9.4.
- [x] Convert Subset26 to ReqIF.
- [ ] Find someone to create a plug-in that processes the generated ReqIF to extract the section numbers (Michael if no one else is found).
# Stakeholders
- Product Owner: Bernd
- V&V: Jan Welte
- Modeling: Uwe Steinke
# Major Use Cases

**Note:** UC-Initial-Subset-Import needs to be provided urgently, but UC-Subset-Update can be delivered much later.  We don't expect updates more often than once or twice a year.
## Actor(s):
- Administrator
## UC-Initial-Subset-Import

**Description:** Convert a Word-based document into a ProR-readable ReqIF-Model.
## UC-Subset-Update

**Description:** Update a ReqIF-Model with an updated Word document.  We assume that the section numbering has not changed and expect traces (if any) to stay intact.
# Possible solutions

As discussed with Bernd on 5-Dec-2013, possible solutions include (the favorite being selected):
1. [ ] Adapt existing scripts DB has for importing the Subset into DOORS.  Reexport as ReqIF with DOORS 9.4.
2. [ ] Adapt existing scripts DB has for importing the Subset into DOORS.  Reexport as RIF with DOORS 9.2.  Convert RIF to ReqIF.
3. [ ] Create a specialized Plug-In for openETCS that reads Word and writes ReqIF.
4. [ ] Create a generic Plug-In for ProR that reads Word and writes ReqIF.
5. [x] Import the Subset directly into DOORS (no further scripts required).  Export as ReqIF with DOORS 9.4.  Process further with a plug-in (to be written), to extract section headings, to be used as IDs.
