### ISSUE TITLE
Milestone Release ToolSprint 4

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#247]
Milestone releases do not increase the version number, they are identified by their qualifier
- [x] Enter milestone qualifier
- [x] Trigger a new build
- [ ] Perform all manual tests (TODO for every project: Create a list of manual tests)
  Test the installer (i.e. a fresh install succeeds)
  - [x] Windows 64 
  - [ ] Windows 32 
  - [x] Linux 64
  - [ ] Linux 32
  - [ ] MacOS 64
  - [ ] MacOS 32
  
  Test the updater (i.e. an update succeeds)
  - [x] Windows 64 
  - [ ] Windows 32 
  - [x] Linux 64
  - [ ] Linux 32
  - [ ] MacOS 64
  - [ ] MacOS 32
- [x] Clean up the issue tracker: roll all unresolved issues in the next sprint
- [x] Close the milestone.
- [x] Create a release on github
- [ ] Publish release notes: These should contain the relevant commits, as well as the list of issues resolved in the sprint.
- [x] Upload the milestone build to the github release
- [ ] Link the latest release on the respective download page
- [ ] Announce release
- [ ] Update this list by new discovered steps https://github.com/openETCS/ecosystem/wiki/Release-Checklist
- [x] Copy this content as an issues to the next milestone
