### ISSUE TITLE
Document the tool chain Roadmap

### ISSUE THREAD

**Issue by cecilebraun** [openETCS/toolchain#248]
The tool chain needs an high level view of the goal to be achieved.
- [x] Look at the document tool chain architecture as a starting point
- [x] write the document
- [ ] launch the review
