### ISSUE TITLE
Integrate Tracing Plugin into Jenkins Build

### ISSUE THREAD

**Issue by jastram** [openETCS/toolchain#299]
A first version of the tracing plugin (#273) is complete.  Currently, this resides on a dedicated branch (tracing).

*_Notes:_ *
- The plug-in needs features of the (not yet released) version 0.10.0.  To accommodate for this, I changed the update site in the target platform (see #298).
- The functionality resides in a single plug-in.  I didn't create a dedicated feature for it, but added it to the org.openetcs.core.feature . I leave it up to the build team to create a dedicated feature - I don't think it's necessary.
- I tested the built by running the maven scripts locally, and by installing the resulting executable (Linux 64), which works fine.
- There are unit tests, which won't compile.  Actually, they do (and pass), but as the test code is currently not included in the RMF SDK feature, the required code is missing.  There is no pom, so this does not disturb the build.

**Tasks:**

The following needs to be done:
- [ ] Please merge the branch tracing into master, if you consider it fit
- [ ] Test the maven build locally.
- [ ] Ensure that RMF 0.10.0 and tracing 0.1.0 are included
- [ ] Trigger a Jenkins build.

Thanks!
