### ISSUE TITLE
Add sysml constraint checker to product specification

### ISSUE THREAD

**Issue by astante** [openETCS/toolchain#312]
I've put a plugin which checks a SysML model for certain properties on the repository. Plugin uses the Eclipse Validation Framework and currently contains only a small list of constraints that are checked. A Wiki Page which describes the plugin and all the constraints will be set up.

The plugin can be found at:
`tool/bundles/org.openetcs.sysml.constraints´
## TODO
- [x] Add Plug-In to top-level openETCS feature
- [x] Add Plug-In to Jenkins and make sure it builds correctly.
- [ ] Either add the documentation to the [Documentation page](https://github.com/openETCS/toolchain/wiki/Documentation), or at least provide a link from the documentation to your exhaustive documentation.
- [ ] Make sure the use of the Plug-In is part of the WP3 modeling process
